#!/bin/tcsh

cd motionCorrect.results

mean_files=( pb02.**.volreg+orig**.BRIK )

outputFileName=$(printf '3dMean -prefix meanTs+orig %s' ${mean_files[0]} )

for ((i=1; i<=${#mean_files[@]}; i++)); do
     
    outputFileName=$(printf '%s %s ' ${outputFileName} ${mean_files[i]} )
   
done

echo ${outputFileName}

${outputFileName}

3dAFNItoNIFTI meanTs+orig

rm meanTs+orig.BRIK
rm meanTs+orig.HEAD

cd ..




